#!/usr/bin/env ruby

fastlane_version "1.96.0"
default_platform :ios

platform :ios do
  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "make a beta build"
  lane :beta_build do
    match
    gym(scheme: "Release", clean: true)
  end

  desc "submit a beta build"
  lane :beta do
    increment_build_number
    gym(scheme: "Release", clean: true)
    pilot(skip_waiting_for_build_processing: true)
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameittest
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
